language: go
go:
    - "1.9"
    - "1.10"

script:
    - go test -timeout 30s -coverprofile=coverage.txt github.com/prebid/go-gdpr/vendorconsent

after_success:
  - bash <(curl -s https://codecov.io/bash)
