language: go
go:
    - "1.9"
    - "1.10"

before_install:
  - go get github.com/mattn/goveralls

script:
    - go test -timeout 30s -coverprofile=profile.cov github.com/prebid/go-gdpr/vendorconsent
    - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci

