language: go
go:
    - "1.9"
    - "1.10"

script:
    - go test -timeout 30s github.com/prebid/go-gdpr/vendorconsent
    - go test -timeout 30s github.com/prebid/go-gdpr/vendorlist
    - go tool vet -source vendorconsent
    - go tool vet -source vendorlist
